# Generated by Django 3.0 on 2021-04-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='no_preview_image.png', null=True, upload_to='../static/images/'),
        ),
    ]
