# Generated by Django 3.0 on 2021-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210427_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='no_preview_image.png', null=True, upload_to='images/'),
        ),
    ]
