# Generated by Django 3.0 on 2021-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210427_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='no_preview_image.png', upload_to='covers/'),
        ),
    ]
