# Generated by Django 3.0 on 2021-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210427_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='article_image.jpg', upload_to='covers/'),
        ),
    ]
