# Generated by Django 3.0 on 2021-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210427_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='/no_preview_image.png', upload_to='covers/'),
        ),
    ]
