# Generated by Django 3.0 on 2021-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20210428_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
