// articles
export const ARTICLES_LIST_REQUEST = "ARTICLES_LIST_REQUEST"
export const ARTICLES_LIST_SUCCESS = "ARTICLES_LIST_SUCCESS"
export const ARTICLES_LIST_FAIL = "ARTICLES_LIST_FAIL"

export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST"
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS"
export const ARTICLE_DETAILS_FAIL = "ARTICLE_DETAILS_FAIL"

export const ARTICLES_CREATE_REQUEST = "ARTICLES_CREATE_REQUEST"
export const ARTICLES_CREATE_SUCCESS = "ARTICLES_CREATE_SUCCESS"
export const ARTICLES_CREATE_FAIL = "ARTICLES_CREATE_FAIL"

export const ARTICLE_DELETE_REQUEST = 'ARTICLE_DELETE_REQUEST'
export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS'
export const ARTICLE_DELETE_FAIL = 'ARTICLE_DELETE_FAIL'

export const ARTICLE_EDIT_REQUEST = 'ARTICLE_EDIT_REQUEST'
export const ARTICLE_EDIT_SUCCESS = 'ARTICLE_EDIT_SUCCESS'
export const ARTICLE_EDIT_FAIL = 'ARTICLE_EDIT_FAIL'

// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user account details
export const USER_ACCOUNT_REQUEST = "USER_ACCOUNT_REQUEST"
export const USER_ACCOUNT_SUCCESS = "USER_ACCOUNT_SUCCESS"
export const USER_ACCOUNT_FAIL = "USER_ACCOUNT_FAIL"

// update user account detials
export const UPDATE_USER_ACCOUNT_REQUEST = "UPDATE_USER_ACCOUNT_REQUEST"
export const UPDATE_USER_ACCOUNT_SUCCESS = "UPDATE_USER_ACCOUNT_SUCCESS"
export const UPDATE_USER_ACCOUNT_FAIL = "UPDATE_USER_ACCOUNT_FAIL"
export const UPDATE_USER_ACCOUNT_RESET = "UPDATE_USER_ACCOUNT_RESET"
